From New.generatedproof.hashtriemap Require Import hashtriemap.
From New.proof Require Import sync.
From New.proof.sync Require Import atomic.

Section proof.
Context `{hG: heapGS Σ, !ffi_semantics _ _} `{!globalsGS Σ} {go_ctx: GoContext}.

#[global] Instance : IsPkgInit hashtriemap := define_is_pkg_init True%I.
#[global] Instance : GetIsPkgInitWf hashtriemap := build_get_is_pkg_init_wf.

(* Auto-generated by proof-setup *)
Lemma wp_HashTrieMap__initHT (ht: loc) :
  {{{ is_pkg_init hashtriemap }}}
    ht @ (ptrT.id hashtriemap.HashTrieMap.id) @ "initHT" #()
  {{{ RET #(); True }}}.
Proof. Admitted.

(* Auto-generated by proof-setup *)
Lemma wp_HashTrieMap__initSlow (ht: loc) :
  {{{ is_pkg_init hashtriemap }}}
    ht @ (ptrT.id hashtriemap.HashTrieMap.id) @ "initSlow" #()
  {{{ RET #(); True }}}.
Proof. Admitted.

(* Auto-generated by proof-setup *)
Lemma wp_hashInt (key: w64) (seed: w64) :
  {{{ is_pkg_init hashtriemap }}}
    @! hashtriemap.hashInt #key #seed
  {{{ (a: w64), RET (#a); True }}}.
Proof. Admitted.

(* Auto-generated by proof-setup *)
Lemma wp_HashTrieMap__Load (ht: loc) (key: w64) :
  {{{ is_pkg_init hashtriemap }}}
    ht @ (ptrT.id hashtriemap.HashTrieMap.id) @ "Load" #key
  {{{ (a: w64) (b: bool), RET (#a, #b); True }}}.
Proof. Admitted.

(* Auto-generated by proof-setup *)
Lemma wp_HashTrieMap__LoadOrStore (ht: loc) (key: w64) (value: w64) :
  {{{ is_pkg_init hashtriemap }}}
    ht @ (ptrT.id hashtriemap.HashTrieMap.id) @ "LoadOrStore" #key #value
  {{{ (a: w64) (b: bool), RET (#a, #b); True }}}.
Proof. Admitted.

(* Auto-generated by proof-setup *)
Lemma wp_HashTrieMap__expand (ht: loc) (oldEntry: loc) (newEntry: loc) (newHash: w64) (hashShift: w64) (parent: loc) :
  {{{ is_pkg_init hashtriemap }}}
    ht @ (ptrT.id hashtriemap.HashTrieMap.id) @ "expand" #oldEntry #newEntry #newHash #hashShift #parent
  {{{ (a: loc), RET (#a); True }}}.
Proof. Admitted.

(* Auto-generated by proof-setup *)
Lemma wp_HashTrieMap__Store (ht: loc) (key: w64) (old: w64) :
  {{{ is_pkg_init hashtriemap }}}
    ht @ (ptrT.id hashtriemap.HashTrieMap.id) @ "Store" #key #old
  {{{ RET #(); True }}}.
Proof. Admitted.

(* Auto-generated by proof-setup *)
Lemma wp_HashTrieMap__Swap (ht: loc) (key: w64) (new: w64) :
  {{{ is_pkg_init hashtriemap }}}
    ht @ (ptrT.id hashtriemap.HashTrieMap.id) @ "Swap" #key #new
  {{{ (a: w64) (b: bool), RET (#a, #b); True }}}.
Proof. Admitted.

(* Auto-generated by proof-setup *)
Lemma wp_HashTrieMap__CompareAndSwap (ht: loc) (key: w64) (old: w64) (new: w64) :
  {{{ is_pkg_init hashtriemap }}}
    ht @ (ptrT.id hashtriemap.HashTrieMap.id) @ "CompareAndSwap" #key #old #new
  {{{ (a: bool), RET (#a); True }}}.
Proof. Admitted.

(* Auto-generated by proof-setup *)
Lemma wp_HashTrieMap__LoadAndDelete (ht: loc) (key: w64) :
  {{{ is_pkg_init hashtriemap }}}
    ht @ (ptrT.id hashtriemap.HashTrieMap.id) @ "LoadAndDelete" #key
  {{{ (a: w64) (b: bool), RET (#a, #b); True }}}.
Proof. Admitted.

(* Auto-generated by proof-setup *)
Lemma wp_HashTrieMap__Delete (ht: loc) (key: w64) :
  {{{ is_pkg_init hashtriemap }}}
    ht @ (ptrT.id hashtriemap.HashTrieMap.id) @ "Delete" #key
  {{{ RET #(); True }}}.
Proof. Admitted.

(* Auto-generated by proof-setup *)
Lemma wp_HashTrieMap__CompareAndDelete (ht: loc) (key: w64) (old: w64) :
  {{{ is_pkg_init hashtriemap }}}
    ht @ (ptrT.id hashtriemap.HashTrieMap.id) @ "CompareAndDelete" #key #old
  {{{ (a: bool), RET (#a); True }}}.
Proof. Admitted.

(* Auto-generated by proof-setup *)
Lemma wp_HashTrieMap__find (ht: loc) (key: w64) (hash: w64) (checkValue: bool) (value: w64) :
  {{{ is_pkg_init hashtriemap }}}
    ht @ (ptrT.id hashtriemap.HashTrieMap.id) @ "find" #key #hash #checkValue #value
  {{{ (a: loc) (b: w64) (c: loc) (d: loc), RET (#a, #b, #c, #d); True }}}.
Proof. Admitted.

(* Auto-generated by proof-setup *)
Lemma wp_HashTrieMap__All (ht: loc) :
  {{{ is_pkg_init hashtriemap }}}
    ht @ (ptrT.id hashtriemap.HashTrieMap.id) @ "All" #()
  {{{ (a: func.t), RET (#a); True }}}.
Proof. Admitted.

(* Auto-generated by proof-setup *)
Lemma wp_HashTrieMap__Range (ht: loc) (yield: func.t) :
  {{{ is_pkg_init hashtriemap }}}
    ht @ (ptrT.id hashtriemap.HashTrieMap.id) @ "Range" #yield
  {{{ RET #(); True }}}.
Proof. Admitted.

(* Auto-generated by proof-setup *)
Lemma wp_HashTrieMap__iter (ht: loc) (i: loc) (yield: func.t) :
  {{{ is_pkg_init hashtriemap }}}
    ht @ (ptrT.id hashtriemap.HashTrieMap.id) @ "iter" #i #yield
  {{{ (a: bool), RET (#a); True }}}.
Proof. Admitted.

(* Auto-generated by proof-setup *)
Lemma wp_HashTrieMap__Clear (ht: loc) :
  {{{ is_pkg_init hashtriemap }}}
    ht @ (ptrT.id hashtriemap.HashTrieMap.id) @ "Clear" #()
  {{{ RET #(); True }}}.
Proof. Admitted.

(* Auto-generated by proof-setup *)
Lemma wp_newIndirectNode (parent: loc) :
  {{{ is_pkg_init hashtriemap }}}
    @! hashtriemap.newIndirectNode #parent
  {{{ (a: loc), RET (#a); True }}}.
Proof. Admitted.

(* Auto-generated by proof-setup *)
Lemma wp_indirect__empty (i: loc) :
  {{{ is_pkg_init hashtriemap }}}
    i @ (ptrT.id hashtriemap.indirect.id) @ "empty" #()
  {{{ (a: bool), RET (#a); True }}}.
Proof. Admitted.

(* Auto-generated by proof-setup *)
Lemma wp_newEntryNode (key: w64) (value: w64) :
  {{{ is_pkg_init hashtriemap }}}
    @! hashtriemap.newEntryNode #key #value
  {{{ (a: loc), RET (#a); True }}}.
Proof. Admitted.

(* Auto-generated by proof-setup *)
Lemma wp_entry__lookup (e: loc) (key: w64) :
  {{{ is_pkg_init hashtriemap }}}
    e @ (ptrT.id hashtriemap.entry.id) @ "lookup" #key
  {{{ (a: w64) (b: bool), RET (#a, #b); True }}}.
Proof. Admitted.

(* Auto-generated by proof-setup *)
Lemma wp_entry__lookupWithValue (e: loc) (key: w64) (value: w64) (checkValue: bool) :
  {{{ is_pkg_init hashtriemap }}}
    e @ (ptrT.id hashtriemap.entry.id) @ "lookupWithValue" #key #value #checkValue
  {{{ (a: w64) (b: bool), RET (#a, #b); True }}}.
Proof. Admitted.

(* Auto-generated by proof-setup *)
Lemma wp_entry__swap (head: loc) (key: w64) (new: w64) :
  {{{ is_pkg_init hashtriemap }}}
    head @ (ptrT.id hashtriemap.entry.id) @ "swap" #key #new
  {{{ (a: loc) (b: w64) (c: bool), RET (#a, #b, #c); True }}}.
Proof. Admitted.

(* Auto-generated by proof-setup *)
Lemma wp_entry__compareAndSwap (head: loc) (key: w64) (old: w64) (new: w64) :
  {{{ is_pkg_init hashtriemap }}}
    head @ (ptrT.id hashtriemap.entry.id) @ "compareAndSwap" #key #old #new
  {{{ (a: loc) (b: bool), RET (#a, #b); True }}}.
Proof. Admitted.

(* Auto-generated by proof-setup *)
Lemma wp_entry__loadAndDelete (head: loc) (key: w64) :
  {{{ is_pkg_init hashtriemap }}}
    head @ (ptrT.id hashtriemap.entry.id) @ "loadAndDelete" #key
  {{{ (a: w64) (b: loc) (c: bool), RET (#a, #b, #c); True }}}.
Proof. Admitted.

(* Auto-generated by proof-setup *)
Lemma wp_entry__compareAndDelete (head: loc) (key: w64) (value: w64) :
  {{{ is_pkg_init hashtriemap }}}
    head @ (ptrT.id hashtriemap.entry.id) @ "compareAndDelete" #key #value
  {{{ (a: loc) (b: bool), RET (#a, #b); True }}}.
Proof. Admitted.

(* Auto-generated by proof-setup *)
Lemma wp_node__entry (n: loc) :
  {{{ is_pkg_init hashtriemap }}}
    n @ (ptrT.id hashtriemap.node.id) @ "entry" #()
  {{{ (a: loc), RET (#a); True }}}.
Proof. Admitted.

(* Auto-generated by proof-setup *)
Lemma wp_node__indirect (n: loc) :
  {{{ is_pkg_init hashtriemap }}}
    n @ (ptrT.id hashtriemap.node.id) @ "indirect" #()
  {{{ (a: loc), RET (#a); True }}}.
Proof. Admitted.

End proof.
